version: "3.8"

services:
  # Serviço Front
  frontend:
    build:
      context: ./src/app
    ports:
      - "3000:3000"
    env_file:
      - .env 
    depends_on:
      - backend-golang
    networks:
      - app-network

  # Serviço Backend
  backend-golang:
    build:
      context: ./src/backend/golang/
    ports:
      - "9000:9000"
    env_file:
      - .env 
    depends_on:
      - db 
    networks:
      - app-network

  backend-model:
    build:
      context: ./src/backend/modelo/
    ports:
      - "8000:8000"
    env_file:
      - .env 
    depends_on:
      - db
    networks:
      - app-network

  # Serviço Banco de Dados
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./src/backend/dependencies/mongo/data/db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=golang-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
