version: "3.8"

services:
  # Serviço Front
  frontend:
    build:
      context: ./src/app 
    ports:
      - "3000:3000"
    environment:
      - ENV=development
    depends_on:
      - backend-golang
    networks:
      - app-network

  # Serviço Backend
  backend-golang:
    build:
      context: ./src/backend/golang/
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb://db:27017/golang-db
    depends_on:
      - db 
    networks:
      - app-network

  # Serviço Backend Modelo
  backend-model:
    build:
      context: ./src/backend/modelo/
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  # Serviço Banco de Dados
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./src/backend/dependencies/mongo/data/db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=golang-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge # Usar bridge para comunicação entre os serviços
